name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test docker-action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
      - name: Run docker-action
        uses: ./
